[general]
live_config_reload = true

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux new-session -s today"]

[font]
size = 14.0

[window]
startup_mode = "Fullscreen"
option_as_alt = "OnlyLeft"

[scrolling]
history = 50000

[colors.primary]
background = "#000000"

[cursor]
style = { shape = "Block", blinking = "Off" }
